language: python
python:
    - "2.6"
    - "2.7"
install: "pip install -r requirements.txt"
before_script: pip install coverage
script: nosetests --with-coverage
after_script:
    - pip install scrutinizer-ocular
    - ocular --data-file ".coverage"

