log:
  level: 1
  path: "./"


# actions to use
actions:
  sub: True
  metadata: True
  convert : True

# Type of media - TV/Movie
type: "TV"

# standard language to use
# ISO 639 format
language:
  video: "eng"
  audio: "eng"
  subtitle: ["eng"]


# Which modules to use for stuff
modules:
  metadata_fetch: "trakt"
  metadata_add: "atomicparsley"
  add: "itunes"
  subtitle: "subtitle"
  notification: "growl"
  convert: "ffmpeg"

# trakt.tv info
trakt:
  key: 'xxxx'
  addToWatchlist: false
  username: 'username'
  password: 'password' # This needs to be a sha1 of your trakt.tv password!


# itunes settings
# if addDirect is set to tru it uses applescript to add it to iTunes
# else it moves the file to the path in path
# Automatically Add to iTunes.localized is a folder iTunes uses to add stuff automatically from
itunes:
  path: '~/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/'
  addDirect: true

