log:
  level: 1
  path: "./"

temp:
  path: "./"

# Type of media - TV/Movie
type: "TV"

# standard language to use
# ISO 639-1 format
language:
  video: "en"
  audio: "en"
  subtitle: "en"


# Which modules to use for stuff
modules:
  metadata: "trakt"
  addTo: "itunes"
  subtitle: "subliminal"

# trakt.tv info
trakt:
  key: 'xxxx'
  addToWatchlist: true
  username: 'username'
  password: 'password'


# itunes settings
# if addDirect is set to tru it uses applescript to add it to iTunes
# else it moves the file to the path in path
# Automatically Add to iTunes.localized is a folder iTunes uses to add stuff automatically from
itunes:
  path: '$HOME/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/'
  addDirect: true